```{r knitsetup, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}
opts_knit$set(base.dir='./', fig.path='', out.format='md')
opts_chunk$set(prompt=TRUE, comment='', results='markup')
# See yihui.name/knitr/options for more Knitr options.
##### Put other setup R code here


# end setup chunk
```
---
title: "預先登錄研究發表模式"
author: "Sau-Chin Chen"
output: html_document
---

示範如何實踐可重製研究之前，我先簡單介紹近年有學者倡議，並已有學術期刊實際運作的預先登錄研究(pre-registered study)發表模式。取材自Chris Chambers在2014年於[APS發表的簡報][1]，一件研究專案從開始計畫到發表，分為兩階段的投稿審查程序：第一階段相當於計畫書審查，論文緒論與研究方法是主要內容；第二階段檢視實際結果與預期的差異。第一階段的審查重點有傳統論文審查重視的假設之學術重要性，方法與分析細節的合理性，混淆變項的控制等，也要求支持最後結果具備高統計檢定力的證據。通過第一階段審查的稿件，期刊方先給予原則性接受(in-principle acceptance, IPA)。第二階段的審查重點是作者得到結果的過程與第一階段規劃的異同，混淆變項的控制是否成功，以及實際結果有無改變預期獲得的結論，通過才能被期刊方正式接受。

預先登錄研究發表模式讓一項研究從一開始就以相當程度公開於同儕之間，Chris Chambers的簡報提到此模式能解決傳統發表模式，為追求「漂亮結果」而造成的各種弊病。這部分值得寫一篇文章介紹，而我在此介紹預先登錄研究的目的，是讓讀者明白為何我要區分狹義與廣義的可重製研究：狹義可重製是第二階段過程的所有中間產物，達到完整公開的各項條件。廣義可重製延伸包含第一階段的計畫、研究材料的公開。而網際網路協作平台的成熟，讓進行可重製研究成為研究者之間的良性競合機制。示範內容也以開放科學平台(Open Science Framework)[已發表於Science的論文專案][2]為例，深入解析這套專案的運作流程。下文以RP:P簡稱這個專案。


[1]: https://osf.io/2gesj/ "Chris, Chambers. The Importance of Study Pre-Registration in Hypothesis-Driven Research."

[2]: https://osf.io/ezcuj/ "Reproducibility Project: Psychology"
